### ISSUE TITLE
[BUG] Port not being free on app kill

### ISSUE THREAD

**Issue by sansyrox** [sansyrox/robyn#183]
**Description**
Run a web server on any port and then press "Ctrl+C".

Then `lsof -i tcp:PORT_NUMBER`, e.g. `lsof -i tcp:5000` for 5000 port.

You will have to manually kill the process.

**Expected Behavior**
This should not happen.

**Comment by Dmourn** [comment]
I noticed this as well as many processes being spawned after press Ctrl+C.
This issue is caused in processpool.py. I thought it may be caused by not calling stop on the event loop ([python docs](https://docs.python.org/3/library/asyncio-eventloop.html?highlight=run_forever#asyncio.loop.run_forever))

I added some print statements and found that the call to `run_forever()` only triggers **after** pressing Ctrl+C.

```
    print("Starting Server")
    server.start(socket, workers)
    print("Calling run_forever() after Ctrl-C") <- This prints
    asyncio.get_event_loop().run_forever()
    print("DEAD CODE run_forever() called ") <- This does not

```

commenting out the call to `run_forever()` "fixes" the issue.

**Comment by sansyrox** [comment]
Hi @Dmourn ,

Thank you for helping with the issue :D

> commenting out the call to run_forever() "fixes" the issue.

Calling `stop` from an exception handler could probably help. But I don't think we should remove `run_forever()` call.

Another culprit that I can think of is me using `unwrap()` very heavily in the code. 

But thank you for pointing this out! 😄

**Comment by Dmourn** [comment]
No problem :) Thanks for making this cool project.

I didn't think that was the solution either. I tried adding `stop` and `os.killpg` in quite a few places, but no luck. So maybe the problem is on the rust side.

**Comment by sansyrox** [comment]
>  Thanks for making this cool project.

I am glad you like it :D

> So maybe the problem is on the rust side.

This is the thing that I will be addressing now. So, should be fixed soon hopefully :D
