### ISSUE TITLE
[BUG] The --dev mode spawns more servers without clearing previous ones.

### ISSUE THREAD

**Issue by sansyrox** [sansyrox/robyn#249]
**Description**

The `--dev` mode is going in infinite recursion when a file is changed in the directory.

To check, you can do
`lsof -i tcp:5000`

**Expected Behavior**

Handle a base case that might have been missed here.

**Environment:**
- Host OS: every 

---

[Optional] **Additional Context**

---

**Comment by guilefoylegaurav** [comment]
Hey @sansyrox I am interested in taking this up. Can you kindly elaborate more on this?
- What kind of result am I expected to see with `--dev` and `lsof -i tcp:5000`?
- It seems that hot reload is not really working on my system? I ran the base_routes.py with the `--dev` flag and cannot see changes being reflecting in the browser immediately when I alter anything in the `integration_tests` directory?

**Comment by sansyrox** [comment]
Hi @guilefoylegaurav ,

Firstly, thank you for your interest.

You will notice changes when you change `integration_tests/base_routes.py` file.

When you type `lsof -i tcp:5000` , you should not see any output after the dev server has been killed. However, if you run `pytest integration_tests`, you will see many processes that have to be killed manually.

**Comment by guilefoylegaurav** [comment]
Hello @sansyrox 

> However, if you run `pytest integration_tests`, you will see many processes that have to be killed manually

- This problem is coming up because in the **teardown** in **conftest.py**, `process.terminate()` has been used which does not kill the child processes spawned

- Replacing `process.terminate()` with `os.killpg(os.getpgid(process.pid), signal.SIGKILL)` would solve the problem

- Also the pytest fixtures inside **configtest.py** have to be scoped to **session** level

Please feel free to let me know what your thoughts are regarding this

**Comment by sansyrox** [comment]
@guilefoylegaurav , great spot. I had fixed this issue thrice and it still appeared, so I assumed it would be the same this time too. :rofl: 

Do you want to create a PR for the same?

**Comment by guilefoylegaurav** [comment]
Sure! If you say so, I'm ready to raise a PR

**Comment by sansyrox** [comment]
@guilefoylegaurav , perfect then :D
