### ISSUE TITLE
Microsoft Defender Antivirus  Trojan:Script/Sabsik.FL.B!ml

### ISSUE THREAD

**Issue by mn3711698** [sansyrox/robyn#542]
os windows 11
Microsoft Defender Antivirus 

Trojan:Script/Sabsik.FL.B!ml
file: C:\Program Files\Python311\Lib\site-packages\robyn\robyn.cp311-win_amd64.pyd

0.33 is alert  Trojan:Script/Sabsik.FL.B!ml
0.32 is ok

**Comment by sansyrox** [comment]
This is the first time I am seeing this 😅 

We just released v0.34.0 - @mn3711698 , can you check if that is triggering the alarm too?

**Comment by graydoubt** [comment]
Hey guys, totally unrelated, I just googled "Trojan:Script/Sabsik.FL.B!ml" to find more about what that trojan is, and came across this very post. 

The game Deep Rock Galactic on Steam was suddenly triggering a Windows Defender alarm and refused to start. There's other folks with the same issue: https://steamcommunity.com/app/548430/discussions/1/6516193260171976107/

I'm only mentioning this because it might be a bunch of false positives across the board, potentially a recent Windows Defender update. Or maybe Skynet is about to end us all.

Cheers!

**Comment by sansyrox** [comment]
Loll. Thanks @graydoubt 😄 

I will be closing this. Windows anti virus is always annoying. And the funny part is that it has improved since the last time I used it. And was 10 years ago!!

**Comment by sansyrox** [comment]
@mn3711698 , feel free to open this issue if the anti virus still complains :D
